Use any key to exit a blank slide
oddbird/slide-deck pull request #21
Opened 2024-01-11 18:36 UTC by mirisuzanne

![](https://source.unsplash.com/featured/?cute,animal&nah)

## Related Issue(s)

Fixes #20 

## Steps to test/reproduce

- Hit `.` or `,` to enter blank screen
- Hit any key to exit, without any other impact on the presentation

2024-01-11 19:43 UTC, jamesnw requested changes
This works when the blank slide is triggered with a shortcut, but not when it's triggered with a slide-event button- `<button slide-event="blankSlide">blankSlide</button>`.

In that case, the button retains focus, and since our keyup event is attached to the body, and the button stops propagation of the event, the #keyEventActions is never run. The user needs to click on the blank slide or re-trigger the button with Enter or Space bar.

I'm not sure what the solution is here- could we move the focus to the body, or to the blank slide (although that's an ::after pseudoelement), when the blank slide is opened?

2024-01-11 19:48 UTC, mirisuzanne commented
@jamesnw what if we use a blank-slide dialog in the shadow-dom with a close button inside it? Then the blank slide would go in the top-layer, and move focus into the dialog, and we could add the special event listener there? Similar to our special control-panel-exiting listener?

2024-01-11 19:52 UTC, jamesnw commented
That sounds like a good solution to me. What styles would the close button have? For this purpose, I'm thinking it could make sense to have the button be the white/black full screen element itself, with no text?

2024-01-15 02:28 UTC, jamesnw approved these changes
This works really well! 

I added an example of a slotted blank slide, and was initially surprised that the full screen styles weren't translated over. My recommendation would be to add a note that the styles in `adoptShadowStyles` are a good starting point, but it makes sense to have it be a blank slate.

2024-01-15 02:28 UTC, jamesnw commented on slide-deck.js
> +  static adoptShadowStyles = (node) => {
Should this be private?

2024-01-15 17:23 UTC, mirisuzanne commented
@jamesnw I made some updates here based on your notes:

- `adoptShadowStyles` is now private
- I went ahead and applied only the full-screen styles to the slotted blank, I think your first instinct was right there. The shadow styles will still just be defaults, easy enough to override from the light dom
- While I was at it, I simplified and organized the styles some. There was redundant stuff in there. And I figured the little top-right 'x' is enough to avoid any exit confusion, without being distracting.

Maybe @stacyk or @dvdherron wants to review those styles as well?

2024-01-15 18:40 UTC, stacyk reviewed
To confirm, the blank screen keyboard shortcuts do not work the same in the custom control panel example. They both go to a blank white screen, but never the blank black screen. I wasn't sure if that is intentional?

You can see the left border on the custom example blank screen. Not sure if we want to add/move the `border: 0` values to  

```
[part=blank-slide],
::slotted([slot=blank-slide]) 
```

![Screenshot 2024-01-15 at 12 22 35 PM](https://github.com/oddbird/slide-deck/assets/1581694/22035eff-f7fa-4603-89a4-020cc43c7b71)

2024-01-15 18:49 UTC, mirisuzanne commented on slide-deck.js
> +      [part=close-blank-slide] {
I don't know. Changing the cursor on buttons is contentious. I like it, but I've heard a11y folks say it's incorrect.

2024-01-15 18:52 UTC, mirisuzanne commented
@stacyk I applied the border and color scheme to the slotted element. Does that look better?

2024-01-15 19:04 UTC, stacyk commented on slide-deck.js
> +      [part=close-blank-slide] {
I like it too, but since pointer is for links, then we shouldn't rock the boat.

2024-01-15 19:16 UTC, merged