Track view settings in URL parameters
oddbird/slide-deck pull request #47
Opened 2024-05-22 23:25 UTC by mirisuzanne

![](https://source.unsplash.com/featured/?cute,animal&snake)

## Related Issue(s)

- Fixes #34

## Steps to test/reproduce

I decided to keep the attribute as the 'source of truth', since the actual styles are based on an attribute selector. Currently:

- When accessing the `slideView` property, the query parameter takes precedence, then the sessionStorage, then the attribute, and finally the default (or specified) `publicView`.
- On-load we check the `slideView`, and update the attribute to match. 
- When the `slideView` is explicitly set (which is what the view buttons do), we update all three (parameter, sessionStorage, and attr).

That means it's possible for them to get out of sync if changed directly without the setter, which I think is ok? I don't think we need to watch for changes on any of them to update the others?

2024-05-28 14:59 UTC, jamesnw requested changes
Works well, just a few questions and nits

2024-05-28 22:04 UTC, mirisuzanne commented on slide-deck.js
> +  }
Maybe we should discuss at standup. I'm not sure I know exactly what the options/tradeoffs are here.

2024-05-28 22:05 UTC, mirisuzanne commented on slide-deck.js
> +    this.setAttribute('slide-view', view);
Yeah, I didn't want to be overriding other params to make this update - so probably makes sense to convert the setter to a function.

2024-05-30 16:13 UTC, jamesnw commented
@mirisuzanne I've updated the navigation handling to match what we talked about.

2024-05-30 16:13 UTC, jamesnw approved these changes

2024-05-30 16:22 UTC, merged